name: Build and Release PDF

on:
  release:
    types: [created]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended
      
      - name: Install non-free fonts
        run: |
          sudo apt-get install -y texlive-fonts-extra-links
      
      - name: Build PDF
        run: |
          pdflatex tutorial.tex
          pdflatex tutorial.tex
      
      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        with:
          files: tutorial.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
